# Analise dos dados

In [2]:
import pandas as pd

In [5]:
cols = [
 "age",
"workclass",
"fnlwgt",
"education",
"education-num",
"marital-status",
"occupation",
"relationship",
"race",
"sex",
"capital-gain",
"capital-loss",
"hours-per-week",
"native-country",
"income" ]
cols_order = [
    "fnlwgt",
    "education-num",
    "capital-gain",
    "capital-loss",
"hours-per-week",
 "age",
"workclass",
"education",
"marital-status",
"occupation",
"relationship",
"race",
"sex",
"native-country",
"income" ]


credit_file = "./adult/adult.data"
df = pd.read_csv(credit_file,names=cols, header=None)

In [6]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [16]:
df[cols_order].head()

fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  age  \
0   83311             13             0             0              13   50   
1  215646              9             0             0              40   38   
2  234721              7             0             0              40   53   
3  338409             13             0             0              40   28   
4  284582             14             0             0              40   37   

           workclass   education       marital-status          occupation  \
0   Self-emp-not-inc   Bachelors   Married-civ-spouse     Exec-managerial   
1            Private     HS-grad             Divorced   Handlers-cleaners   
2            Private        11th   Married-civ-spouse   Handlers-cleaners   
3            Private   Bachelors   Married-civ-spouse      Prof-specialty   
4            Private     Masters   Married-civ-spouse     Exec-managerial   

     relationship    race      sex  native-country  income  
0         Husband   White     Male   United-States   <=50K  
1   Not-in-family   White     Male   United-States   <=50K  
2         Husband   Black     Male   United-States   <=50K  
3            Wife   Black   Female            Cuba   <=50K  
4            Wife   White   Female   United-States   <=50K

In [30]:
df.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32560.000000  3.256000e+04   32560.000000  32560.000000  32560.000000   
mean      38.581634  1.897818e+05      10.080590   1077.615172     87.306511   
std       13.640642  1.055498e+05       2.572709   7385.402999    402.966116   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178315e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783630e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370545e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    32560.000000  
mean        40.437469  
std         12.347618  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [64]:
df.iloc[13,]['native-country']

' ?'

In [9]:
#df["native-country"][df['native-country'] == " ?"]
for x in df.columns:
    df.drop(df[x][df[x]==" ?"].index, inplace=True)
    if df[x].dtypes == "object": df[x] = df[x].str.replace("-", "")

In [10]:
for x in df.columns:
    print(df[x][df[x]==" ?"])
    

Series([], Name: age, dtype: int64)
Series([], Name: workclass, dtype: object)
Series([], Name: fnlwgt, dtype: int64)
Series([], Name: education, dtype: object)
Series([], Name: education-num, dtype: int64)
Series([], Name: marital-status, dtype: object)
Series([], Name: occupation, dtype: object)
Series([], Name: relationship, dtype: object)
Series([], Name: race, dtype: object)
Series([], Name: sex, dtype: object)
Series([], Name: capital-gain, dtype: int64)
Series([], Name: capital-loss, dtype: int64)
Series([], Name: hours-per-week, dtype: int64)
Series([], Name: native-country, dtype: object)
Series([], Name: income, dtype: object)


In [23]:
df = df[cols_order]

# Splitting data: descriptive & target features

In [24]:
l = len(df.columns)-1

In [19]:
l

14

In [53]:
descriptive = df.iloc[:,0:l].values
target = df.iloc[:,l].values

In [27]:
descriptive

array([[77516, 13, 2174, ..., ' White', ' Male', ' UnitedStates'],
       [83311, 13, 0, ..., ' White', ' Male', ' UnitedStates'],
       [215646, 9, 0, ..., ' White', ' Male', ' UnitedStates'],
       ...,
       [151910, 9, 0, ..., ' White', ' Female', ' UnitedStates'],
       [201490, 9, 0, ..., ' White', ' Male', ' UnitedStates'],
       [287927, 9, 15024, ..., ' White', ' Female', ' UnitedStates']],
      dtype=object)

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [42]:
columns = []
for i, cols in enumerate(df.columns[:-1]):
    if df[cols].dtypes == 'object': columns.append(i)

In [33]:
columns

[6, 7, 8, 9, 10, 11, 12, 13]

In [51]:
column_transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), columns)],
                                       remainder = 'passthrough',
                                       sparse_threshold=0
                                       )

In [54]:
descriptive = np.array(column_transformer.fit_transform(descriptive))

In [55]:
descriptive

array([[0.0, 0.0, 0.0, ..., 0, 40, 39],
       [0.0, 0.0, 0.0, ..., 0, 13, 50],
       [0.0, 0.0, 1.0, ..., 0, 40, 38],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 40, 58],
       [0.0, 0.0, 1.0, ..., 0, 20, 22],
       [0.0, 0.0, 0.0, ..., 0, 40, 52]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
labelEncoder = LabelEncoder()
descriptive[:,0] = labelEncoder.fit_transform(descriptive[:,0])

Conforme está dito nas apresentações, aqui fizemos uma conversão de Categoria para Numérico

Agora vamos ver todos os que são Categorias e converter

In [20]:
for i, cols in enumerate(df.columns[:-1]):
    if df[cols].dtypes == 'object':
        descriptive[:,i] = labelEncoder.fit_transform(descriptive[:,i])

Todos os objetos foram convertidos para labelencoder

In [21]:
descriptive[:,0]

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,

In [22]:
encoder = LabelEncoder()
target = encoder.fit_transform(target)

In [23]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [24]:
encoder.inverse_transform(target)

array(['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+

# Train Test Split

In [30]:
from sklearn.model_selection import train_test_split

In [37]:
descriptive_train, descriptive_test, target_train, target_test = train_test_split(descriptive, target, test_size=0.5, random_state=0)

In [38]:
descriptive_train

array([[0, 24.33, 2.5, ..., 0, 24.33, 456],
       [1, 65.42, 11.0, ..., 0, 65.42, 0],
       [0, 16.33, 0.21, ..., 0, 16.33, 1],
       ...,
       [1, 22.67, 1.585, ..., 0, 22.67, 0],
       [1, 25.58, 0.335, ..., 0, 25.58, 0],
       [0, 65.17, 14.0, ..., 0, 65.17, 1400]], dtype=object)

## Data Standardization

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
standard_scaler = StandardScaler()

In [43]:
descriptive_train[:,:] = standard_scaler.fit_transform(descriptive_train[:,:])
descriptive_test[:,:] = standard_scaler.fit_transform(descriptive_test[:,:])

In [44]:
descriptive_train

array([[-1.3650083747903758, -0.6420352833357559, -0.5079135742947734,
        ..., -0.31362502409358894, -0.6420352833357559,
        -0.13705659221525052],
       [0.7325962378462111, 2.781611064256619, 1.3145667084799537, ...,
        -0.31362502409358894, 2.781611064256619, -0.2536199744496808],
       [-1.3650083747903758, -1.3086006467024873, -0.9989112034187881,
        ..., -0.31362502409358894, -1.3086006467024873,
        -0.25336435299741233],
       ...,
       [0.7325962378462111, -0.7803475962343525, -0.7040982164993469,
        ..., -0.31362502409358894, -0.7803475962343525,
        -0.2536199744496808],
       [0.7325962378462111, -0.5378844453097041, -0.972110022789748, ...,
        -0.31362502409358894, -0.5378844453097041, -0.2536199744496808],
       [-1.3650083747903758, 2.7607808966514082, 1.9577950435769162, ...,
        -0.31362502409358894, 2.7607808966514082, 0.10425005872620172]],
      dtype=object)

# Naive Bayes Algorithm

In [46]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(descriptive_train, target_train)

GaussianNB()

In [48]:
prediction = classifier.predict(descriptive_test)

## Accuracy and Matrix

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy = accuracy_score(target_test, prediction)
matrix = confusion_matrix(target_test, prediction)

In [53]:
accuracy

0.8

In [55]:
matrix

array([[101,  50],
       [ 17, 167]])

In [56]:
prediction

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,

In [58]:
target_test

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,

In [61]:
!jupyter nbconvert --to=python credit.ipynb

[NbConvertApp] Converting notebook credit.ipynb to python
[NbConvertApp] Writing 4578 bytes to credit.py
